# SPDX-FileCopyrightText: 2021 Carson Black <uhhadd@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

defmodule Protocol.Chat.V1.ChatServiceService do
	def endpoints do
		[
			{"CreateGuild", "/protocol.chat.v1.ChatService/CreateGuild", false, false, Protocol.Chat.V1.CreateGuildRequest, Protocol.Chat.V1.CreateGuildResponse},
			{"CreateInvite", "/protocol.chat.v1.ChatService/CreateInvite", false, false, Protocol.Chat.V1.CreateInviteRequest, Protocol.Chat.V1.CreateInviteResponse},
			{"CreateChannel", "/protocol.chat.v1.ChatService/CreateChannel", false, false, Protocol.Chat.V1.CreateChannelRequest, Protocol.Chat.V1.CreateChannelResponse},
			{"CreateEmotePack", "/protocol.chat.v1.ChatService/CreateEmotePack", false, false, Protocol.Chat.V1.CreateEmotePackRequest, Protocol.Chat.V1.CreateEmotePackResponse},
			{"GetGuildList", "/protocol.chat.v1.ChatService/GetGuildList", false, false, Protocol.Chat.V1.GetGuildListRequest, Protocol.Chat.V1.GetGuildListResponse},
			{"GetGuild", "/protocol.chat.v1.ChatService/GetGuild", false, false, Protocol.Chat.V1.GetGuildRequest, Protocol.Chat.V1.GetGuildResponse},
			{"GetGuildInvites", "/protocol.chat.v1.ChatService/GetGuildInvites", false, false, Protocol.Chat.V1.GetGuildInvitesRequest, Protocol.Chat.V1.GetGuildInvitesResponse},
			{"GetGuildMembers", "/protocol.chat.v1.ChatService/GetGuildMembers", false, false, Protocol.Chat.V1.GetGuildMembersRequest, Protocol.Chat.V1.GetGuildMembersResponse},
			{"GetGuildChannels", "/protocol.chat.v1.ChatService/GetGuildChannels", false, false, Protocol.Chat.V1.GetGuildChannelsRequest, Protocol.Chat.V1.GetGuildChannelsResponse},
			{"GetChannelMessages", "/protocol.chat.v1.ChatService/GetChannelMessages", false, false, Protocol.Chat.V1.GetChannelMessagesRequest, Protocol.Chat.V1.GetChannelMessagesResponse},
			{"GetMessage", "/protocol.chat.v1.ChatService/GetMessage", false, false, Protocol.Chat.V1.GetMessageRequest, Protocol.Chat.V1.GetMessageResponse},
			{"GetEmotePacks", "/protocol.chat.v1.ChatService/GetEmotePacks", false, false, Protocol.Chat.V1.GetEmotePacksRequest, Protocol.Chat.V1.GetEmotePacksResponse},
			{"GetEmotePackEmotes", "/protocol.chat.v1.ChatService/GetEmotePackEmotes", false, false, Protocol.Chat.V1.GetEmotePackEmotesRequest, Protocol.Chat.V1.GetEmotePackEmotesResponse},
			{"UpdateGuildInformation", "/protocol.chat.v1.ChatService/UpdateGuildInformation", false, false, Protocol.Chat.V1.UpdateGuildInformationRequest, Google.Protobuf.Empty},
			{"UpdateChannelInformation", "/protocol.chat.v1.ChatService/UpdateChannelInformation", false, false, Protocol.Chat.V1.UpdateChannelInformationRequest, Google.Protobuf.Empty},
			{"UpdateChannelOrder", "/protocol.chat.v1.ChatService/UpdateChannelOrder", false, false, Protocol.Chat.V1.UpdateChannelOrderRequest, Google.Protobuf.Empty},
			{"UpdateMessageText", "/protocol.chat.v1.ChatService/UpdateMessageText", false, false, Protocol.Chat.V1.UpdateMessageTextRequest, Google.Protobuf.Empty},
			{"AddEmoteToPack", "/protocol.chat.v1.ChatService/AddEmoteToPack", false, false, Protocol.Chat.V1.AddEmoteToPackRequest, Google.Protobuf.Empty},
			{"DeleteGuild", "/protocol.chat.v1.ChatService/DeleteGuild", false, false, Protocol.Chat.V1.DeleteGuildRequest, Google.Protobuf.Empty},
			{"DeleteInvite", "/protocol.chat.v1.ChatService/DeleteInvite", false, false, Protocol.Chat.V1.DeleteInviteRequest, Google.Protobuf.Empty},
			{"DeleteChannel", "/protocol.chat.v1.ChatService/DeleteChannel", false, false, Protocol.Chat.V1.DeleteChannelRequest, Google.Protobuf.Empty},
			{"DeleteMessage", "/protocol.chat.v1.ChatService/DeleteMessage", false, false, Protocol.Chat.V1.DeleteMessageRequest, Google.Protobuf.Empty},
			{"DeleteEmoteFromPack", "/protocol.chat.v1.ChatService/DeleteEmoteFromPack", false, false, Protocol.Chat.V1.DeleteEmoteFromPackRequest, Google.Protobuf.Empty},
			{"DeleteEmotePack", "/protocol.chat.v1.ChatService/DeleteEmotePack", false, false, Protocol.Chat.V1.DeleteEmotePackRequest, Google.Protobuf.Empty},
			{"DequipEmotePack", "/protocol.chat.v1.ChatService/DequipEmotePack", false, false, Protocol.Chat.V1.DequipEmotePackRequest, Google.Protobuf.Empty},
			{"EquipEmotePack", "/protocol.chat.v1.ChatService/EquipEmotePack", false, false, Protocol.Chat.V1.EquipEmotePackRequest, Google.Protobuf.Empty},
			{"JoinGuild", "/protocol.chat.v1.ChatService/JoinGuild", false, false, Protocol.Chat.V1.JoinGuildRequest, Protocol.Chat.V1.JoinGuildResponse},
			{"LeaveGuild", "/protocol.chat.v1.ChatService/LeaveGuild", false, false, Protocol.Chat.V1.LeaveGuildRequest, Google.Protobuf.Empty},
			{"TriggerAction", "/protocol.chat.v1.ChatService/TriggerAction", false, false, Protocol.Chat.V1.TriggerActionRequest, Google.Protobuf.Empty},
			{"SendMessage", "/protocol.chat.v1.ChatService/SendMessage", false, false, Protocol.Chat.V1.SendMessageRequest, Protocol.Chat.V1.SendMessageResponse},
			{"QueryHasPermission", "/protocol.chat.v1.ChatService/QueryHasPermission", false, false, Protocol.Chat.V1.QueryPermissionsRequest, Protocol.Chat.V1.QueryPermissionsResponse},
			{"SetPermissions", "/protocol.chat.v1.ChatService/SetPermissions", false, false, Protocol.Chat.V1.SetPermissionsRequest, Google.Protobuf.Empty},
			{"GetPermissions", "/protocol.chat.v1.ChatService/GetPermissions", false, false, Protocol.Chat.V1.GetPermissionsRequest, Protocol.Chat.V1.GetPermissionsResponse},
			{"MoveRole", "/protocol.chat.v1.ChatService/MoveRole", false, false, Protocol.Chat.V1.MoveRoleRequest, Protocol.Chat.V1.MoveRoleResponse},
			{"GetGuildRoles", "/protocol.chat.v1.ChatService/GetGuildRoles", false, false, Protocol.Chat.V1.GetGuildRolesRequest, Protocol.Chat.V1.GetGuildRolesResponse},
			{"AddGuildRole", "/protocol.chat.v1.ChatService/AddGuildRole", false, false, Protocol.Chat.V1.AddGuildRoleRequest, Protocol.Chat.V1.AddGuildRoleResponse},
			{"ModifyGuildRole", "/protocol.chat.v1.ChatService/ModifyGuildRole", false, false, Protocol.Chat.V1.ModifyGuildRoleRequest, Google.Protobuf.Empty},
			{"DeleteGuildRole", "/protocol.chat.v1.ChatService/DeleteGuildRole", false, false, Protocol.Chat.V1.DeleteGuildRoleRequest, Google.Protobuf.Empty},
			{"ManageUserRoles", "/protocol.chat.v1.ChatService/ManageUserRoles", false, false, Protocol.Chat.V1.ManageUserRolesRequest, Google.Protobuf.Empty},
			{"GetUserRoles", "/protocol.chat.v1.ChatService/GetUserRoles", false, false, Protocol.Chat.V1.GetUserRolesRequest, Protocol.Chat.V1.GetUserRolesResponse},
			{"StreamEvents", "/protocol.chat.v1.ChatService/StreamEvents", true, true, Protocol.Chat.V1.StreamEventsRequest, Protocol.Chat.V1.Event},
			{"GetUser", "/protocol.chat.v1.ChatService/GetUser", false, false, Protocol.Chat.V1.GetUserRequest, Protocol.Chat.V1.GetUserResponse},
			{"GetUserBulk", "/protocol.chat.v1.ChatService/GetUserBulk", false, false, Protocol.Chat.V1.GetUserBulkRequest, Protocol.Chat.V1.GetUserBulkResponse},
			{"GetUserMetadata", "/protocol.chat.v1.ChatService/GetUserMetadata", false, false, Protocol.Chat.V1.GetUserMetadataRequest, Protocol.Chat.V1.GetUserMetadataResponse},
			{"ProfileUpdate", "/protocol.chat.v1.ChatService/ProfileUpdate", false, false, Protocol.Chat.V1.ProfileUpdateRequest, Google.Protobuf.Empty},
			{"Typing", "/protocol.chat.v1.ChatService/Typing", false, false, Protocol.Chat.V1.TypingRequest, Google.Protobuf.Empty},
			{"PreviewGuild", "/protocol.chat.v1.ChatService/PreviewGuild", false, false, Protocol.Chat.V1.PreviewGuildRequest, Protocol.Chat.V1.PreviewGuildResponse},
			{"BanUser", "/protocol.chat.v1.ChatService/BanUser", false, false, Protocol.Chat.V1.BanUserRequest, Google.Protobuf.Empty},
			{"KickUser", "/protocol.chat.v1.ChatService/KickUser", false, false, Protocol.Chat.V1.KickUserRequest, Google.Protobuf.Empty},
			{"UnbanUser", "/protocol.chat.v1.ChatService/UnbanUser", false, false, Protocol.Chat.V1.UnbanUserRequest, Google.Protobuf.Empty},
		]
	end
end
